"""
Django settings for SmartSightProject project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================
# 🔐 SECURITY
# ==========================
SECRET_KEY = config("SECRET_KEY", default="dev-secret-key")  
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.0.104",         # Local network
    "172.22.93.1",           # WSL/VM bridge
    "a248facecc97.ngrok-free.app",  # Ngrok domain for mobile
]

# ==========================
# 📦 INSTALLED APPS
# ==========================
INSTALLED_APPS = [
    # Django default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_extensions",

    # Local apps
    "core",   # Main app (Users, etc.)
]

# ==========================
# ⚙️ MIDDLEWARE
# ==========================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be first for CORS
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SmartSightProject.urls"

# ==========================
# 🎨 TEMPLATES
# ==========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # optional custom templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SmartSightProject.wsgi.application"

# ==========================
# 🛢 DATABASE
# ==========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="smart_sight"),
        "USER": config("DB_USER", default="capstone"),
        "PASSWORD": config("DB_PASSWORD", default="capstone"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# ==========================
# 🔑 PASSWORD VALIDATION
# ==========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==========================
# 🌍 INTERNATIONALIZATION
# ==========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"  # ⏰ Adjusted to PH
USE_I18N = True
USE_TZ = True

# ==========================
# 📂 STATIC & MEDIA FILES
# ==========================
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # optional
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ==========================
# 🔧 DEFAULTS
# ==========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================
# 🌐 CORS CONFIG
# ==========================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "accept",
    "origin",
    "user-agent",
]
CORS_EXPOSE_HEADERS = ["content-type", "authorization"]

# ==========================
# 🔑 REST FRAMEWORK
# ==========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# ✅ Fix for React Native / mobile requests
APPEND_SLASH = True


ALLOWED_HOSTS = ["127.0.0.1", "localhost", "93f53e5593dd.ngrok-free.app"]
